/**
 * Created by Thomas on 2018/10/23.
 */

export const STORE_UPDATE_TEST = 'STORE_UPDATE_TEST'
export const STORE_UPDATE_TEST_SUCCESS = 'STORE_UPDATE_TEST_SUCCESS'
export const STORE_UPDATE_TEST_FAILURE = 'STORE_UPDATE_TEST_FAILURE'

// 更新选中索引
export const UPDATE_TAB_ACTIVE = 'UPDATE_TAB_ACTIVE'
// 获取进货的列表数据
export const FILTER_PURCHASE_DATA_LIST = 'FILTER_PURCHASE_DATA_LIST'
export const FILTER_PURCHASE_DATA_LIST_SUCCESS = 'FILTER_PURCHASE_DATA_LIST_SUCCESS'
export const FILTER_PURCHASE_DATA_LIST_FAILURE = 'FILTER_PURCHASE_DATA_LIST_FAILURE'
